### ISSUE TITLE
The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by vipulrawat** [alexa-js/alexa-app-example#3]
I deployed in heroku using the deployed button in your README file. The /test is showing in the html page with all the things but when I set my HTTPS endpoint in the configuration of my skill I am getting this error.
I don't know what endpoint to set. Please Help.
_## `The remote endpoint could not be called, or the response it returned was invalid.`_

**Comment by tejashah88** [comment]
@vipulrawat The remote endpoint should be at `https://<app-name>.herokuapp.com/test`, where `<app-name>` is the name that you specify on heroku. The path `/test` is specified by this line:

`var alexaApp = new alexa.app("test");`

Changing "test" will thus change the path endpoint.

There's some more documentation about configuring express to work with alexa-app [here](https://github.com/alexa-js/alexa-app#express). If you have any other questions, feel free to ask.
